# Generated by Django 4.2 on 2024-05-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('products.can_edit_publication_status', 'может отменять публикацию продукта'), ('products.can_edit_description', 'может отменять публикацию продукта'), ('products.can_change_category', 'может менять категорию любого продукта')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
