# Generated by Django 4.2 on 2024-05-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('catalog.can_edit_publication_status', 'может отменять публикацию продукта'), ('catalog.can_edit_description', 'может отменять публикацию продукта'), ('catalog.can_change_category', 'может менять категорию любого продукта')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
